#Nexus & Jenkins instalation 
---
- name: Set hostname for the system
  hosts: servers
  become: yes
  tasks:
    - name: Set the system hostname
      hostname:
        name: nexus-jenkins-gitlab-colombia.cem.com.co  #Especificar el nombre del host
    - name: Update /etc/hosts with the new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.0\.1\s+localhost\s+).*$'
        line: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 nexus-jenkins-gitlab-colombia.cem.com.co'
        state: present
    - name: Ensure hostname is consistent in /etc/hostname
      copy:
        content: "nexus-jenkins-gitlab-colombia.cem.com.co\n"
        dest: /etc/hostname

- name: Enable firewalld ports
  hosts: servers
  become: yes
  tasks:
    - name: Enable port 8443/tcp
      firewalld:
        port: 8443/tcp  # Puerto para Nexus https
        permanent: yes
        state: enabled
    - name: Enable port 8445/ttcp
      firewalld:
        port: 8445/tcp # Puerto para Nexus API
        permanent: yes
        state: enabled
    - name: Enable port 8081/tcp
      firewalld:
        port: 8081/tcp # Puerto para Nexus http
        permanent: yes
        state: enabled
    - name: Enable port 8080/tcp
      firewalld:
        port: 8080/tcp # Puerto para Jenkins http
        permanent: yes
        state: enabled
    - name: Recargar firewalld
      command: firewall-cmd --reload


- name: Install tools for Oracle 
  hosts: servers
  become: yes
  tasks:
    - name: Update all package on the system 
      yum:
        name: '*'
        state: latest
    - name: Install tools
      yum:
        name:
          - nano
          - git
          - tree

- name: Setup Nexus on Oracle Linux 8.X
  hosts: servers
  become: yes
  tasks:
    - name: Install Java JDK 1.8
      dnf:
        name: java-1.8.0-openjdk.x86_64
        state: present
    - name: Create user 'nexus'
      user:
        name: nexus
        state: present
    - name: Create directory /opt/app
      file:
        path: /opt/app
        state: directory
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/app/sonartype-nexus.tar.gz
        timeout: 1200
    - name: Extract Nexus
      ansible.builtin.unarchive:
        src: /opt/app/sonartype-nexus.tar.gz
        dest: /opt/app/
        remote_src: yes
    - name: Rename file "nexus-"
      shell: |
        for file in /opt/app/nexus-*; do
          mv "$file" /opt/app/nexus
          echo "Renamed: $file -> /opt/app/nexus"
          break
        done
      args:
        executable: /bin/bash
      register: renamed_result
    - name: Show renamed result
      debug:
        var: renamed_result.stdout
    - name: change Nexus file permissions in /opt/app
      command: chown -R nexus:nexus /opt/app/nexus
    - name: change file permissionsdel sonatype-work in /opt/app
      command: chown -R nexus:nexus /opt/app/sonatype-work
    - name: Define Nexus user in nexus.rc
      lineinfile:
        path: /opt/app/nexus/bin/nexus.rc
        regexp: '^run_as_user='
        line: 'run_as_user="nexus"'
        create: yes
    - name: Create systemd service file for Nexus
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          User=nexus
          Group=nexus
          ExecStart=/opt/app/nexus/bin/nexus start
          ExecStop=/opt/app/nexus/bin/nexus stop
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target

- name: Set and verify Nexus Service
  hosts: servers
  tasks:
    - name: systemctl daemon-reload
      command: systemctl daemon-reload
      register: result
    - name: systemctl start nexus
      command: systemctl start nexus
    - name: systemctl enable nexus
      command: systemctl enable nexus
    - name: systemctl status nexus
      command: systemctl status nexus
      register: nexus_status
    - name: Output status Nexus
      debug:
        msg: "{{ nexus_status.stdout_lines }}"

- name: Add config file for https certificates
  hosts: servers
  tasks:
    - name: Add config file for https certificates - Need launch manually  # Se requiere la configuración manual del archiivo BASH para generar los certificados
      copy:
        src: /root/ansible/files/certificate-https.sh
        dest: /opt/app/nexus/etc/ssl

- name: Install Jenkins and dependencies
  hosts: servers
  become: yes
  tasks:
    - name: Download Jenkins repositories
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      args:
        creates: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins key GPG
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    - name: Install Jenkins dependencies 
      yum:
        name:
          - java-17-openjdk
        state: present
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
    - name: System daemons reload
      command: systemctl daemon-reload
    - name: Enable Jenkins Service
      systemd:
        name: jenkins
        enabled: yes

- name: Version Java for Jenkins
  hosts: servers
  become: yes
  tasks:
    - name: Rename file "jenkins.service-"
      shell: |
        cp /usr/lib/systemd/system/jenkins.service /usr/lib/systemd/system/jenkins.service.bkp
      args:
        executable: /bin/bash
      register: renamed_result
    - name: Show renamed result
      debug:
        var: renamed_result.stdout
    - name: Add JAVA_HOME to file jenkins.service
      copy:
        src: /root/ansible/files/jenkins-file-config/jenkins.service
        dest: /usr/lib/systemd/system/
    - name: System daemons reload
      command: systemctl daemon-reload
    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started

    - name: Check Jenkins Service Status
      shell: systemctl status jenkins
      register: jenkins_status
    - name: Show Jenkins Service Status
      debug:
        msg: "{{ jenkins_status.stdout_lines }}"

- name: Set and verify Nexus Service
  hosts: servers
  tasks:
    - name: systemctl status nexus
      command: systemctl status nexus
      register: nexus_status
    - name: Output status Nexus
      debug:
        msg: "{{ nexus_status.stdout_lines }}"
    - name: Port status - ss -antpl
      command: ss -antpl
      register: ss_output
    - name: Status ports ss -antpl
      debug:
        msg: "{{ ss_output.stdout }}"

- name: Get password and ip address for Jenkins and Nexus services
  hosts: servers
  tasks:
    - name: Get Nexus admin password
      slurp:
        src: /opt/app/sonatype-work/nexus3/admin.password
      register: admin_password_nexus
    - name: Decode and store Nexus admin password
      set_fact:
        nexus_admin_password: "{{ admin_password_nexus.content | b64decode }}"
    - name: Gather IP address
      set_fact:
        nexus_ip_address: "{{ ansible_default_ipv4.address }}"
    - name: Nexus credentials
      debug:
        msg: "User: admin || Password: {{ nexus_admin_password }} || IP Address: http://{{ nexus_ip_address }}:8081"

    - name: Get Jenkins root password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password_jenkins
    - name: Decode and store Jenkins admin password
      set_fact:
        jenkins_admin_password: "{{ admin_password_jenkins.content | b64decode }}"
    - name: Gather IP address
      set_fact:
        jenkins_ip_address: "{{ ansible_default_ipv4.address }}"
    - name: Jenkins credentials
      debug:
        msg: "User: root || Password: {{ jenkins_admin_password }} || IP Address: http://{{ jenkins_ip_address }}:8080"

##pasos adicionales 

#en Nexus se debe ejecutar el arvhivo certificate-https.sh especificando los nombres de los certificados dentro de la carpeta /opt/app/nexus/etc/ssl
#Luego se deben modificar los archivos nexus.propierties cambiando la contraseña que se especificó anteriormente 
#por último se debe modificar el archivo jetty-https 
#Se reinician los damons y el servicio de nexus
# esperamos unos minutos y comporbamos los puertos ss -antpl, deben estar los puertos 8443 y 8445 activos
#Con esto ya podemos ir a la consola web con la ip y el puerto 8443

