---
- name: Set hostname for the system
  hosts: servers
  become: yes
  tasks:
    - name: Set the system hostname
      hostname:
        name: nexus-jenkins-gitlab-colombia.cem.com.co  #Especificar el nombre del host
    - name: Update /etc/hosts with the new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.0\.1\s+localhost\s+).*$'
        line: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 nexus-jenkins-gitlab-colombia.cem.com.co'
        state: present
    - name: Ensure hostname is consistent in /etc/hostname
      copy:
        content: "nexus-jenkins-gitlab-colombia.cem.com.co\n"
        dest: /etc/hostname
